version: "3"
services:
  music-explore:
    build: .
    ports:
      - "3000:3000"
    image: music-explore-back:v1.0
    environment:
      - DOCKER_COMPOSE=true
  mongo:
    image: mongo
    ports:
      - "27017:27017"
